### PR TITLE
#1 Fixed the folder structure of the react src folder

### LINKED ISSUE #1: Fix folder structure in repo
Components should go in a `/components` folder
e.g. Modal.js should be inside `/src/components/Modal/Modal.js`

### PR DESCRIPTION
**Pull request by dennisxu54**
closes #1

### CODE REVIEW

File: src/App.js [hunk 1]
```diff
@@ -1,10 +1,9 @@
 import "./App.css";
 import React, { useEffect } from "react";
 import { useState } from "react";
-import Search from "./search";
-import LoadList from "./loadList";
-import ConfirmBox from "./ConfirmBox";
-import NewModal from "./Modal";
+import Search from "./components/Search/Search";
+import LoadList from "./components/LoadList/LoadList";
+import NewModal from "./components/Modal/Modal";
```
Comment (egodihc) [inline src/App.js:6]: Did you sort these imports?

**Comment by egodihc** [comment]
You should also separate the css of different components into separate css files.

**Comment by egodihc** [comment]
LGTM

**Review by egodihc — CHANGES_REQUESTED** [review]
test example
